### ISSUE TITLE
It is not clear what RolesTree are

### ISSUE THREAD

**Issue by mitar** [AppWorkshop/meteor-accounts-admin-materializecss#6]
It seems they are just permission about who can edit membership of some roles. But from the name it could mean also that there are permission checks you can do afterwards. For example, if user is in role `foo`, and role `foo` is parent of role `bar`, then checking for user for role `bar` should succeed if user is in role `foo`, but does not have `bar` assigned.

**Comment by cunneen** [comment]
That's right, it is there in the Readme file but a bit hard to find. It should probably be moved above the History.

Also this functionality will be moved into a separate package at some point.

https://github.com/cunneen/meteor-accounts-admin-materializecss#roles-hierarchy
